USE [ubpd_base]
GO

/****** Object:  StoredProcedure [dbo].[CONSULTA_INML_DES]    Script Date: 27/11/2023 10:01:54 p. m. ******/
DROP PROCEDURE [dbo].[CONSULTA_INML_DES]
GO

/****** Object:  StoredProcedure [dbo].[CONSULTA_INML_DES]    Script Date: 27/11/2023 10:01:54 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- =============================================
-- Author:		Juan Manuel Maestre JImenez
-- Create date: 27/11/2023
-- Description:	Realiza la consulta de las personas desaparecidas de la fuente INML_DES
-- =============================================
CREATE   PROCEDURE [dbo].[CONSULTA_INML_DES]
WITH RECOMPILE 
AS
BEGIN
  SET NOCOUNT ON;
  SELECT [DES_DARE_NUMERO_RADICADO]
      ,[DES_DARE_FECHA_RADICADO]
      ,[DES_DARE_ESTADO_DESAPARICION]
      ,[DES_DARE_USUARIO_REGISTRA]
      ,[DES_DARE_ENTIDAD_REGISTRA]
      ,[DES_DARE_FECHA_REPORTE]
      ,[DES_DARE_CLASIFICACION_DESAPARICION]
      ,[DES_DARE_ESTATURA]
      ,[DES_DARE_INGRESA_IDENTIFICADO]
      ,[DES_DARE_NOMBRES]
      ,[DES_DARE_PRIMER_APELLIDO]
      ,[DES_DARE_SEGUNDO_APELLIDO]
      ,[DES_DARE_SEXO]
      ,[DES_DARE_TIPO_DOCUMENTO]
      ,[DES_DARE_NUMERO_DOCUMENTO]
      ,[DES_DARE_PAIS_EXPEDICION]
      ,[DES_DARE_DEPARTAMENTO_EXPEDICION]
      ,[DES_DARE_MUNICIPIO_EXPEDICION]
      ,[DES_DARE_PAIS_DE_NACIMIENTO]
      ,[DES_DARE_MUNICIPIO_DE_NACIMIENTO]
      ,[DES_DARE_DEPARTAMENTO_DE_NACIMIENTO]
      ,[DES_DARE_EDAD_RANGOS]
      ,[DES_DARE_UNIDAD_EDAD]
      ,[DES_DARE_ANCESTRO_RACIAL]
      ,[DES_DARE_PERTENENCIA_ETNICA]
      ,[DES_DARE_CONDICION_VULNERABILIDAD]
      ,[DES_DARE_OCUPACION]
      ,[DES_DARE_ESTADO_CIVIL]
      ,[DES_DARE_ESCOLARIDAD]
      ,[DES_DARE_PROFESION]
      ,[DES_DARE_PAIS_RESIDENCIA]
      ,[DES_DARE_DEPARTAMENTO_RESIDENCIA]
      ,[DES_DARE_MUNICIPIO_RESIDENCIA]
      ,[DES_DARE_DIRECCION_DESAPARECIDO]
      ,[DES_DARE_TELEFONO_RESIDENCIA]
      ,[DES_DARE_FECHA_DESAPARICION]
      ,[DES_DARE_SE_DETERMINA_HORA_DESAPARICION]
      ,[DES_DARE_HORA_DESAPARICION]
      ,[DES_DARE_PRESUNCION_RESPONSABILIDAD]
      ,[DES_DARE_DIRECCION_DESAPARICION]
      ,[DES_DARE_PAIS_DESAPARICION]
      ,[DES_DARE_DEPARTAMENTO_DESAPARICION]
      ,[DES_DARE_MUNICIPIO_DESAPARICION]
      ,[DES_DARE_BARRIO_VEREDA_DESAPARICION]
      ,[DES_DARE_LOCALIDAD_HECHO]
      ,[DES_DARE_ZONA_HECHO]
      ,[DES_DARE_FECHA_NACIMIENTO]
      ,[DES_DARE_RESUMEN_HECHOS]
      ,[DES_DARE_FECHA_DE_CREACION]
      ,[DES_DARE_FECHA_DE_ACTUALIZACION]
      ,[SOUNDEX_ID]
  FROM [dbo].[INMLCF_DES_DATOS_DE_REGISTRO]
	WHERE NOT(
	[DES_DARE_ENTIDAD_REGISTRA] = 'UNIDAD DE BUSQUEDA DE PERSONAS DESAPARECIDAS' AND 
	[DES_DARE_USUARIO_REGISTRA] = 'USUARIOS  _UBPD')

  END
GO


